services:
  postgres_dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: happy_path_postgres_dev
    environment:
      POSTGRES_DB: happy_path_dev
      POSTGRES_USER: happy_path_user
      POSTGRES_PASSWORD: happy_path_dev_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"  # Use different port for dev to avoid conflicts
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./logs:/var/log/postgresql
      - ../../sql:/docker-entrypoint-initdb.d/sql_scripts
    networks:
      - happy_path_dev_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U happy_path_user -d happy_path_dev"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    command: >
      postgres 
      -c log_statement=all 
      -c log_destination=stderr 
      -c log_directory=/var/log/postgresql
      -c logging_collector=on
      -c max_connections=200
      -c shared_buffers=256MB

volumes:
  postgres_dev_data:
    driver: local

networks:
  happy_path_dev_network:
    driver: bridge
